"""Initial

Revision ID: d592111f46ad
Revises: 
Create Date: 2020-12-27 11:07:44.925712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd592111f46ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Products',
    sa.Column('productId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('productname', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('available', 'pending', 'sold', name='productstatus'), nullable=True),
    sa.PrimaryKeyConstraint('productId')
    )
    op.create_table('Users',
    sa.Column('userId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('firstname', sa.String(length=50), nullable=True),
    sa.Column('lastname', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=250), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('userId'),
    sa.UniqueConstraint('username')
    )
    op.create_table('Orders',
    sa.Column('orderId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('productId', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('placed', 'approved', 'delivered', name='orderstatus'), nullable=True),
    sa.Column('isComplete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['productId'], ['Products.productId'], ),
    sa.ForeignKeyConstraint(['userId'], ['Users.userId'], ),
    sa.PrimaryKeyConstraint('orderId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Orders')
    op.drop_table('Users')
    op.drop_table('Products')
    # ### end Alembic commands ###
